spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: mx.gob.nayarit.consumidor.deserializer.VehicularDeserializer
      value-deserializer: mx.gob.nayarit.consumidor.deserializer.VehicularDeserializer

  data:
    mongodb:
      host: localhost
      port: 27017
      database: vehicular
      repositories:
        enabled: true
